import { Box } from "@mui/material";
import Head from "next/head";
import { ReactNode } from "react";
import { FunctionComponent } from "react";
import { Footer } from "../Footer";
import { Topbar } from "../Topbar";

interface Props {
  title: string;
  children: ReactNode;
}

export const Layout = ({ title, children }: Props) => {
  return (
    <Box
      component="div"
      style={{
        background: "#f5f5f5",
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Box
        component="main"
        style={{ padding: "1rem", maxWidth: "1024px", margin: "auto" }}
      >
        {children}
      </Box>
      <Footer />
    </Box>
  );
};
