import { Box } from "@mui/material";
import Head from "next/head";
import {
  ReactNode,
  useRef,
  useImperativeHandle,
  useEffect,
  useState,
} from "react";
import { FunctionComponent } from "react";
import { Footer } from "../Footer";
import { Topbar } from "../Topbar";

import { themeStyled } from "../../styles/themes/styled";

interface Props {
  title: string;
  children: ReactNode;
}

export const Layout = ({ title, children }: Props) => {
  const [hasScrolled, setHasScrolled] = useState(false);

  /* const layoutRef = useRef();

  function handleScroll() {
    setHasScrolled(() => {
      if (layoutRef.current) {
        return layoutRef && layoutRef?.current?.scrollTop > 20;
      }
    });
  } */

  const handleScroll = () => {
    if (!!window) {
      setHasScrolled(() => {
        const pageYOffset = window.pageYOffset;
        return pageYOffset > 50;
      });
    }
  };

  useEffect(() => {
    if (!!window) {
      window.addEventListener("scroll", handleScroll);
      () => window.removeEventListener("scroll", handleScroll);
    }
  });

  return (
    <Box
      component="div"
      style={{
        background: themeStyled.color.background,
        height: "100vh",
        position: "relative",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
      }}
    >
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar hasScrolled={hasScrolled} />
      <Box
        component="main"
        style={{
          width: "100%",
        }}
      >
        {children}
      </Box>
      <Footer />
    </Box>
  );
};
