import { Box } from "@mui/material";
import Head from "next/head";
import { ReactNode } from "react";
import { FunctionComponent } from "react";
import { Footer } from "../Footer";
import { Topbar } from "../Topbar";

import { themeStyled } from "../../styles/themes/styled";

interface Props {
  title: string;
  children: ReactNode;
}

export const Layout = ({ title, children }: Props) => {
  return (
    <Box
      component="div"
      style={{
        background: themeStyled.color.background,
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        position: "relative",
      }}
    >
      <Box
        style={{
          width: "100%",
          height: "20vw",
          minHeight: "15rem",
          backgroundImage: "url(/images/background.png)",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          backgroundPosition: "center 40%",
          position: "absolute",
          top: 0,
          left: 0,
        }}
      />
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Box
        component="main"
        style={{
          padding: "1rem",
          width: "100%",
          maxWidth: themeStyled.breakpoints.desktop,
          margin: "auto",
          position: "relative",
          zIndex: 2,
        }}
      >
        {children}
      </Box>
      <Footer />
    </Box>
  );
};
